# Generated by Django 5.0.9 on 2026-09-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='source_page',
            field=models.CharField(blank=True, choices=[('slc1964', 'Saint Louis College'), ('SLCCSC', 'SLC Central Student Council'), ('SLCstudentHelpDesk', 'SLC Student Help Desk'), ('slcRegistrar', 'SLC Registrar'), ('slccasteitcrim', 'SLC CAS-TE-IT-CRIM'), ('sits.slclu', 'Society of Information Technology Students - SLC La Union')], max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
