# Generated by Django 5.0.9 on 2026-09-07 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_source_page_announcement_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('suspension', 'Class suspension'), ('holiday', 'Holiday'), ('exam', 'Exam schedule'), ('enrollment', 'Enrollment'), ('event', 'Event'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='year_level',
            field=models.CharField(choices=[('all', 'All year levels'), ('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year')], db_index=True, default='all', max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('publisher', 'Publisher')], db_index=True, default='publisher', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('must_change_password', models.BooleanField(default=False)),
                ('temp_password_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'user__username'],
            },
        ),
    ]
