# Generated by Django 5.0.9 on 2026-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_invite_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='section',
            field=models.CharField(choices=[('all', 'All sections'), ('a', 'Section A'), ('b', 'Section B'), ('c', 'Section C'), ('d', 'Section D')], db_index=True, default='all', max_length=10),
        ),
    ]
