# Generated by Django 4.2.29 on 2026-09-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='section',
            field=models.CharField(choices=[('all', 'All sections'), ('a', 'Section A'), ('b', 'Section B'), ('c', 'Section C'), ('d', 'Section D'), ('e', 'Section E')], db_index=True, default='all', max_length=10),
        ),
    ]
